# Docker compose file for local development

version: "3.9"

services:
  auth_backend:
    build: .
    ports:
      - "8000:8000"
    env_file: .env

  auth_db:
    image: postgres:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 5
    env_file:
      - .database.env
    volumes:
      - postgres-data-auth:/var/lib/postgresql/data

  backend-migrate:
    build: .
    depends_on:
      auth_db:
        condition: service_healthy
    entrypoint: [ "alembic", "upgrade", "head" ]
    env_file: .env

volumes:
  postgres-data-auth:
