"""added tables

Revision ID: 06885b6d9b8c
Revises: 
Create Date: 2022-05-22 23:18:33.959841

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "06885b6d9b8c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", "SUPERUSER", name="userrole"),
            nullable=False,
        ),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_full_name"), "user", ["full_name"], unique=False)
    op.create_table(
        "token",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["email"],
            ["user.email"],
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_token_access_token"), "token", ["access_token"], unique=False)
    op.create_index(
        op.f("ix_token_refresh_token"),
        "token",
        ["refresh_token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_refresh_token"), table_name="token")
    op.drop_index(op.f("ix_token_access_token"), table_name="token")
    op.drop_table("token")
    op.drop_index(op.f("ix_user_full_name"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
